### Numpy

numpy는 1차원 이상의 숫자 데이터를 연산하기 위해 만들어진 모듈로 벡터, 행렬 등의 연산을 가능하게 하는 모듈입니다.

numpy를 통해 만들어진 자료형을 넘파이 배열(np.array)라고 부릅니다.

In [1]:
import numpy as np

np.array를 이용하여 숫자가 들어간 리스트를 넘파이 배열로 변환해 줄 수 있습니다.

list 형태에서 불가능했던 사칙연산들이 넘파이 배열 구조에서는 가능해집니다.

In [2]:
arr1 = np.array([1,2,3])
arr2 = np.array([4,5,6])

넘파이 배열의 연산은 elementwise로 동작합니다. 각 배열에 대해 대응되는 원소들 끼리 연산이 진행됩니다.

In [3]:
print(arr1 + arr2)
print(arr1 - arr2)
print(arr1 * arr2)
print(arr1 / arr2)

[5 7 9]
[-3 -3 -3]
[ 4 10 18]
[0.25 0.4  0.5 ]


또한, 1차원의 넘파이 배열은 벡터로써의 기능도 겸하며, 내적과 같은 벡터 연산이 가능합니다.

In [4]:
np.dot(arr1,arr2) #내적

32

이번에는 넘파이 배열을 이용하여 2차원의 배열을 생성해보도록 하겠습니다.

In [5]:
mat1 = np.array([[1,2],[3,4]])
mat2 = np.array([[5,6],[7,8]])

2차원 배열 역시 기본적인 연산은 elementwise하게 진행됩니다.

In [6]:
print(mat1 + mat2)
print(mat1 - mat2)
print(mat1 * mat2)
print(mat1 / mat2)

[[ 6  8]
 [10 12]]
[[-4 -4]
 [-4 -4]]
[[ 5 12]
 [21 32]]
[[0.2        0.33333333]
 [0.42857143 0.5       ]]


2차원의 넘파이 배열은 행렬로써의 기능도 겸하며, 행렬곱과 같은 행렬 연산이 가능합니다

In [9]:
np.matmul(mat1,mat2) ##행렬의 곱셈

array([[19, 22],
       [43, 50]])

Numpy 배열을 통해 이미지를 표현할 수 있습니다.

우리가 아는 이미지는 보통 3차원으로 h(높이), w(길이), c(채널, rgb)로 표현됩니다.

In [11]:
from PIL import Image
image = Image.open("your image!")
image

FileNotFoundError: ignored

In [ ]:
image = np.array(image)
image.shape  ## h, w, c

이미지에서의 연산은 주로 행렬의 곱 형태로 나타납니다.

예를 들어 이미지에 어떤 필터를 씌우고 싶다면, 이미지와 필터를 곱해주면 됩니다.

In [ ]:
g_filter = np.array([])  ## Filter